name: m1client # you probably want to 'snapcraft register <name>'
version: e0880ad
summary: m1client
description: |
  cli utility for to sync M1 test fixture logs, stcrets and update

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic

base: core22

apps:
    m1client:
      command: bin/m1client
      plugs: [network, network-bind]

      
parts:
    m1client:
      source: ./app/
      source-type: local
      plugin: npm
      npm-include-node: true
      npm-node-version: 20.18.0
      stage-packages: 
          - musl
