name: m1tfd1 # you probably want to 'snapcraft register <name>'
version: "1f01cb1d"
summary: M1 test fixture cli utility
description: |
  cli utility for testing M1-3200 in production

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic

base: core22
apps:
    cli:
      command: bin/m1tfc
      plugs: [network, network-bind]

    app:
      command: usr/bin/gui
      plugs: [network, network-bind]
      
parts:
    cli:
      source: ./m1tfc/
      source-type: local
      plugin: npm
      npm-include-node: true
      npm-node-version: 20.18.0
      stage-packages: 
          - musl
          
    app:
      plugin: dump
      source: ./gui
      source-type: local
      stage-packages: 
          - musl
      organize:
        gui : usr/bin/gui
      prime:
      - usr/bin/
      
